config/routes.rb
Rails.application.routes.draw do
  resources :listenings
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/listening.rb
class Listening < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/listenings_controller.rb
class ListeningsController < ApplicationController
  before_action :set_listening, only: [:show, :edit, :update, :destroy]

  # GET /listenings
  # GET /listenings.json
  def index
    @listenings = Listening.all
  end

  # GET /listenings/1
  # GET /listenings/1.json
  def show
  end

  # GET /listenings/new
  def new
    @listening = Listening.new
  end

  # GET /listenings/1/edit
  def edit
  end

  # POST /listenings
  # POST /listenings.json
  def create
    @listening = Listening.new(listening_params)

    respond_to do |format|
      if @listening.save
        format.html { redirect_to @listening, notice: 'Listening was successfully created.' }
        format.json { render :show, status: :created, location: @listening }
      else
        format.html { render :new }
        format.json { render json: @listening.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /listenings/1
  # PATCH/PUT /listenings/1.json
  def update
    respond_to do |format|
      if @listening.update(listening_params)
        format.html { redirect_to @listening, notice: 'Listening was successfully updated.' }
        format.json { render :show, status: :ok, location: @listening }
      else
        format.html { render :edit }
        format.json { render json: @listening.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /listenings/1
  # DELETE /listenings/1.json
  def destroy
    @listening.destroy
    respond_to do |format|
      format.html { redirect_to listenings_url, notice: 'Listening was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_listening
      @listening = Listening.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def listening_params
      params.require(:listening).permit(:name, :file_url)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/listenings_helper.rb
module ListeningsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>KaizenEng</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/listenings/_form.html.erb
<%= form_with(model: listening, local: true) do |form| %>
  <% if listening.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(listening.errors.count, "error") %> prohibited this listening from being saved:</h2>

      <ul>
      <% listening.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :listening_name %>
  </div>

  <div class="field">
    <%= form.label :file_url %>
    <%= form.text_area :file_url, id: :listening_file_url %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/listenings/edit.html.erb
<h1>Editing Listening</h1>

<%= render 'form', listening: @listening %>

<%= link_to 'Show', @listening %> |
<%= link_to 'Back', listenings_path %>

app/views/listenings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listenings</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>File url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @listenings.each do |listening| %>
      <tr>
        <td><%= listening.name %></td>
        <td><%= listening.file_url %></td>
        <td><%= link_to 'Show', listening %></td>
        <td><%= link_to 'Edit', edit_listening_path(listening) %></td>
        <td><%= link_to 'Destroy', listening, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Listening', new_listening_path %>

app/views/listenings/new.html.erb
<h1>New Listening</h1>

<%= render 'form', listening: @listening %>

<%= link_to 'Back', listenings_path %>

app/views/listenings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @listening.name %>
</p>

<p>
  <strong>File url:</strong>
  <%= @listening.file_url %>
</p>

<%= link_to 'Edit', edit_listening_path(@listening) %> |
<%= link_to 'Back', listenings_path %>